"""
Django settings for social_system project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-u=8^k(ktljs4-oq3t=m14em#2kzk3srz&7o_o*o7hhl$en5q*2"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "web_social_service",
    "rest_framework",
    "drf_yasg",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "social_system.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "web_social_service/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "social_system.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "web-social-system",  # Имя вашей БД. Если вы создали черезе psql или IDE свою базу и хотите использовать его - пропишите его имя здесь
        "USER": "student",
        "PASSWORD": "root",
        "HOST": "localhost",
        "PORT": 5432,  # Стандартный порт PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/web_social_service/static/"
STATICFILES_DIRS = [BASE_DIR / "static", "web_social_service/static"]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Настройки для аутентификации
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
}

AWS_STORAGE_BUCKET_NAME = "social-system"
AWS_ACCESS_KEY_ID = "minio"
AWS_SECRET_ACCESS_KEY = "minio124"
AWS_S3_ENDPOINT_URL = "localhost:9000"
MINIO_USE_SSL = False

CSRF_COOKIE_NAME = "csrftoken"  # Имя cookie с CSRF-токеном
CSRF_COOKIE_HTTPONLY = False  # Для возможности доступа через JavaScript
SESSION_COOKIE_NAME = "sessionid"  # Имя cookie для сессии


REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379

CORS_ALLOW_CREDENTIALS = True  # Разрешаем передавать cookies с кросс-доменных запросов
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.56.1:3000",
    "http://192.168.0.10:3000",  # Например, если фронтенд работает на порту 3000
    "https://localhost:3000",
    "https://127.0.0.1:3000",
    "https://192.168.56.1:3000",
    "https://192.168.0.10:3000",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.56.1:3000",
    "http://192.168.0.10:3000",  # Например, если фронтенд работает на порту 3000
    "https://localhost:3000",
    "https://127.0.0.1:3000",
    "https://192.168.56.1:3000",
    "https://192.168.0.10:3000",
]

CORS_ORIGIN_WHITELIST = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.56.1:3000",
    "http://192.168.0.10:3000",  # Например, если фронтенд работает на порту 3000
    "https://localhost:3000",
    "https://127.0.0.1:3000",
    "https://192.168.56.1:3000",
    "https://192.168.0.10:3000",
]

CORS_ALLOW_ALL_ORIGINS = True  # tauri
# CSRF_COOKIE_SECURE = False
# CSRF_TRUSTED_ORIGINS = []
# CSRF_USE_SESSIONS = False
# Используем сессии, основанные на cookies
SESSION_ENGINE = (
    "django.contrib.sessions.backends.db"  # для хранения сессий в базе данных
)
SESSION_COOKIE_HTTPONLY = (
    True  # Для безопасности, чтобы cookie не были доступны через JavaScript
)
SESSION_COOKIE_SECURE = False  # Убедитесь, что на локальном сервере это False, на продакшене должно быть True
SESSION_EXPIRE_AT_BROWSER_CLOSE = (
    False  # Чтобы сессия не закрывалась при закрытии браузера
)
